### ISSUE TITLE
screen flickers when launched in windows cmd

### ISSUE THREAD

**Issue by jeshocarmel** [kylebebak/questionnaire#1]
Between every question the screen actually flickers. I'm not sure whether this is coming from curses or prompters. Can u help me out here Kyle? 

Thanks man

**Comment by kylebebak** [comment]
Hey Jesho, what machine and OS are you running?

**Comment by jeshocarmel** [comment]
@kylebebak windows in Lenovo. But I've moved it to mac and it's okay now.

**Comment by kylebebak** [comment]
Ah that's good =)

I know the bug isn't fixed, but I'm going to close this, because I don't know enough about curses on Windows to fix it.

Thanks for the heads up.
